name: liquidnode-vps             # The name of your Snap package
version: '1.0.0'                  # Version of your project
summary: A powerful VPS solution for personal and project use
description: |
  The Liquid Node VPS is a lightweight, high-performance virtual server
  solution for hosting personal websites, apps, or community-driven projects.
  It provides full control, customization, and reliability without the cloud service jargon.
  
confinement: strict                # Use strict confinement for security and isolation
base: core20                      # This defines the base for your snap (core20 is for Ubuntu 20.04)
architectures:
  - amd64                         # Architecture type

# Define the parts section to describe how to build your app
parts:
  liquid-node-vps:
    plugin: dump                    # Use the dump plugin for simple packaging
    source: .                        # Point to the source directory of your project
    stage-packages:
      - curl
      - libssl-dev
    organize:
      bin/*: $SNAP/bin/             # Organize where binaries go
    build-packages:
      - build-essential             # Any packages needed to build your app

# Define the apps section for the executable commands provided by the Snap
apps:
  liquid-node-vps:
    command: bin/liquid-node-vps     # The executable for your VPS app or service
    plugs:
      - network                     # Network access required
      - network-bind                # Bind to network ports if necessary
      - home                         # Home directory access for configurations

# Define additional sections for dependencies or configurations
plugs:
  network: {}

# Add environment variables if needed (optional)
environment:
  PATH: $SNAP/bin:$PATH
